ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\Ant\Downloads\WhatsApp Image .jpeg")
Sleep(2000)
ControlFocus("Open","","Button1")
Sleep(2000)
ControlClick("Open","","Button1")
Sleep(2000)
ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\Users\Ant\Downloads\WhatsApp Image .jpeg")
Sleep(2000)
ControlFocus("Open","","Button1")
Sleep(2000)
ControlClick("Open","","Button1")

